### ISSUE TITLE
Phoenix still alive?

### ISSUE THREAD

**Issue by CasperOng** [phoenix277yt/PearOS-arch#6]
Hi Phoenix, maybe you forgot who I am. Basically I am a contributor of Arch pearOS. Why you deleted your Discord account and also why you really gave up on this idea? We really want to know. Thanks

**Comment by dakshcs** [comment]
i have not forgotten any of you, im still on discord on an alt, i got bored of linux.

**Comment by CasperOng** [comment]
@phoenix277yt Understand. We now have a new pearOS arch made by alex. Feel free to try it =)
https://github.com/pearOS-archlinux/iso/releases

**Comment by dakshcs** [comment]
pog

**Comment by CasperOng** [comment]
> pog

@phoenix277yt haha. try it out  it is impressive! pearOS is now officially moving to arccccch
